#!/usr/bin/env bash

# author: m7tkr
# last edited: 20240316180751
# purpose: create rc files symlinks
# usage: source <path>/<to>/makelinks

# get script directory
SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") &> /dev/null && pwd)

while read -r; do
    # check if location commented, by so skipping it
    grep -q -e '^#' <<< "$REPLY" && echo "$REPLY" won\'t be created && continue

    # extract folder path
    DIR="${REPLY#*:}"
    DIR=$( eval echo "${DIR%/*}" )

    # extract file name
    FILE="${REPLY##*/}"

    # location/path of target file
    TARGET_FILE_PATH="${REPLY%%:*}"
    TARGET_FILE_PATH="$TARGET_FILE_PATH/$FILE"
    TARGET_FILE_PATH="$SCRIPT_DIR/$TARGET_FILE_PATH"

    # check if symbolic link directory exists
    if [ ! -d "$DIR" ]; then
        # create direcotory in which symlinks will reside
        mkdir -p $DIR
	echo "created directory: $DIR"
    fi

    # finally create symbolic link
    ln -sf "$TARGET_FILE_PATH" "$DIR/$FILE"  
done < "$SCRIPT_DIR"/locations
